/* eslint-disable react/forbid-prop-types */
import Head from 'next/head'
import PropTypes from 'prop-types'
import { getArticleService } from 'article-service-hooks'
import AllArticles from '../components/AllArticles'

export async function getServerSideProps() {
  const articleService = getArticleService()
  const data = await articleService.getAll()

  return {
    props: {
      articles: data
    }
  }
}

export default function HomePage({ articles }) {
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllArticles articles={articles} />
    </>
  )
}

HomePage.propTypes = {
  articles: PropTypes.arrayOf(PropTypes.object).isRequired
}
